// Mock data for development (no API needed)
import type { Order } from '@/types/order';

export const mockCategories = [
  { id: 1, name: 'ยาและสุขภาพ', slug: 'medicine', description: 'ยาและผลิตภัณฑ์สุขภาพ', sortOrder: 1, isActive: true },
  { id: 2, name: 'ความงาม', slug: 'beauty', description: 'ผลิตภัณฑ์ความงาม', sortOrder: 2, isActive: true },
  { id: 3, name: 'เครื่องสำอาง', slug: 'cosmetics', description: 'เครื่องสำอาง', sortOrder: 3, isActive: true },
  { id: 4, name: 'แม่และเด็ก', slug: 'mom-baby', description: 'สินค้าแม่และเด็ก', sortOrder: 4, isActive: true },
  { id: 5, name: 'อาหารเสริม', slug: 'supplements', description: 'อาหารเสริม', sortOrder: 5, isActive: true },
  { id: 6, name: 'อุปกรณ์การแพทย์', slug: 'medical', description: 'อุปกรณ์การแพทย์', sortOrder: 6, isActive: true },
];

export const mockProducts = [
  {
    id: 1,
    sku: 'PARA500-10',
    name: 'ยาพาราเซตามอล 500 มก. (แผง 10 เม็ด)',
    description: 'ยาบรรเทาปวด ลดไข้ สำหรับผู้ใหญ่และเด็กอายุ 12 ปีขึ้นไป',
    retailPrice: 35,
    originalPrice: 50,
    stockQty: 100,
    reservedQty: 0,
    availableQty: 100,
    imageUrl: 'https://placehold.co/400x400/14b8a6/white?text=Paracetamol',
    categoryId: 1,
    categoryName: 'ยาและสุขภาพ',
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    minOrderQty: 1,
    maxOrderQty: 99,
    rating: 4.8,
    reviewCount: 2345,
    soldCount: 12500,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 2,
    sku: 'VITC1000-30',
    name: 'วิตามิน C 1000 mg (ขวด 30 เม็ด)',
    description: 'วิตามิน C ช่วยเสริมภูมิคุ้มกัน ผิวกระจ่างใส',
    retailPrice: 199,
    originalPrice: 299,
    stockQty: 50,
    reservedQty: 0,
    availableQty: 50,
    imageUrl: 'https://placehold.co/400x400/f97316/white?text=Vitamin+C',
    categoryId: 5,
    categoryName: 'อาหารเสริม',
    isActive: true,
    isFeatured: true,
    isNew: true,
    isBestseller: false,
    minOrderQty: 1,
    maxOrderQty: 50,
    rating: 4.9,
    reviewCount: 1890,
    soldCount: 8500,
    createdAt: '2024-02-01',
    updatedAt: '2024-02-01',
  },
  {
    id: 3,
    sku: 'ALCOGEL-500',
    name: 'เจลแอลกอฮอล์ล้างมือ 500ml',
    description: 'เจลล้างมือแอลกอฮอล์ 70% ฆ่าเชื้อโรค',
    retailPrice: 89,
    originalPrice: 120,
    stockQty: 200,
    reservedQty: 0,
    availableQty: 200,
    imageUrl: 'https://placehold.co/400x400/3b82f6/white?text=Alcohol+Gel',
    categoryId: 1,
    categoryName: 'ยาและสุขภาพ',
    isActive: true,
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    minOrderQty: 1,
    maxOrderQty: 99,
    rating: 4.7,
    reviewCount: 3200,
    soldCount: 15000,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: 4,
    sku: 'MASK-50',
    name: 'หน้ากากอนามัย 3 ชั้น (กล่อง 50 ชิ้น)',
    description: 'หน้ากากอนามัยคุณภาพสูง กรองฝุ่น PM2.5',
    retailPrice: 59,
    originalPrice: 99,
    stockQty: 500,
    reservedQty: 0,
    availableQty: 500,
    imageUrl: 'https://placehold.co/400x400/10b981/white?text=Face+Mask',
    categoryId: 1,
    categoryName: 'ยาและสุขภาพ',
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    minOrderQty: 1,
    maxOrderQty: 100,
    rating: 4.6,
    reviewCount: 5600,
    soldCount: 25000,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 5,
    sku: 'COUGH-60',
    name: 'ยาแก้ไอสูตรไม่มีน้ำตาล 60ml',
    description: 'บรรเทาอาการไอ ลดเสมหะ',
    retailPrice: 55,
    originalPrice: 75,
    stockQty: 80,
    reservedQty: 0,
    availableQty: 80,
    imageUrl: 'https://placehold.co/400x400/8b5cf6/white?text=Cough+Syrup',
    categoryId: 1,
    categoryName: 'ยาและสุขภาพ',
    isActive: true,
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    minOrderQty: 1,
    maxOrderQty: 50,
    rating: 4.5,
    reviewCount: 890,
    soldCount: 4200,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: 6,
    sku: 'BALM-20',
    name: 'ยาดมน้ำมันเหลือง 20g',
    description: 'บรรเทาอาการวิงเวียน คลื่นไส้',
    retailPrice: 25,
    originalPrice: 35,
    stockQty: 300,
    reservedQty: 0,
    availableQty: 300,
    imageUrl: 'https://placehold.co/400x400/f59e0b/white?text=Balm',
    categoryId: 1,
    categoryName: 'ยาและสุขภาพ',
    isActive: true,
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    minOrderQty: 1,
    maxOrderQty: 99,
    rating: 4.9,
    reviewCount: 4500,
    soldCount: 18000,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 7,
    sku: 'VITD-60',
    name: 'วิตามิน D3 1000 IU (ขวด 60 เม็ด)',
    description: 'วิตามิน D3 ช่วยดูดซึมแคลเซียม กระดูกแข็งแรง',
    retailPrice: 299,
    originalPrice: 399,
    stockQty: 40,
    reservedQty: 0,
    availableQty: 40,
    imageUrl: 'https://placehold.co/400x400/6366f1/white?text=Vitamin+D',
    categoryId: 5,
    categoryName: 'อาหารเสริม',
    isActive: true,
    isFeatured: true,
    isNew: true,
    isBestseller: false,
    minOrderQty: 1,
    maxOrderQty: 30,
    rating: 4.8,
    reviewCount: 670,
    soldCount: 3200,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 8,
    sku: 'FACEFOAM-100',
    name: 'โฟมล้างหน้าสำหรับผิวแพ้ง่าย 100ml',
    description: 'โฟมล้างหน้าอ่อนโยน ไม่ระคายเคือง',
    retailPrice: 159,
    originalPrice: 229,
    stockQty: 60,
    reservedQty: 0,
    availableQty: 60,
    imageUrl: 'https://placehold.co/400x400/ec4899/white?text=Face+Foam',
    categoryId: 2,
    categoryName: 'ความงาม',
    isActive: true,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    minOrderQty: 1,
    maxOrderQty: 50,
    rating: 4.7,
    reviewCount: 1200,
    soldCount: 5600,
    createdAt: '2024-02-15',
    updatedAt: '2024-02-15',
  },
];

export const mockCart = {
  items: [],
  totalItems: 0,
  totalAmount: 0,
};

export const mockOrders: Order[] = [
  {
    id: 1,
    orderNo: 'RE250315001',
    lineUserId: 'U1234567890abcdef',
    customerName: 'นายสมชาย ใจดี',
    customerPhone: '081-234-5678',
    customerEmail: 'somchai@example.com',
    shippingAddress: {
      name: 'นายสมชาย ใจดี',
      phone: '081-234-5678',
      address: '123/45 ถ.สุขุมวิท ซ.15',
      district: 'คลองเตย',
      province: 'กรุงเทพ',
      postalCode: '10110',
    },
    items: [
      {
        productId: 1,
        sku: 'PARA500-10',
        name: 'ยาพาราเซตามอล 500 มก.',
        imageUrl: 'https://placehold.co/400x400/14b8a6/white?text=Paracetamol',
        price: 35,
        quantity: 2,
        subtotal: 70,
      },
      {
        productId: 2,
        sku: 'VITC1000-30',
        name: 'วิตามิน C 1000 mg',
        imageUrl: 'https://placehold.co/400x400/f97316/white?text=Vitamin+C',
        price: 199,
        quantity: 1,
        subtotal: 199,
      },
    ],
    subtotal: 269,
    shippingFee: 0,
    discountAmount: 0,
    totalAmount: 269,
    status: 'pending',
    paymentMethod: 'promptpay',
    paymentStatus: 'pending',
    createdAt: '2025-03-15T10:30:00Z',
    updatedAt: '2025-03-15T10:30:00Z',
  },
  {
    id: 2,
    orderNo: 'RE250310005',
    lineUserId: 'U1234567890abcdef',
    customerName: 'นายสมชาย ใจดี',
    customerPhone: '081-234-5678',
    customerEmail: 'somchai@example.com',
    shippingAddress: {
      name: 'นายสมชาย ใจดี',
      phone: '081-234-5678',
      address: '123/45 ถ.สุขุมวิท ซ.15',
      district: 'คลองเตย',
      province: 'กรุงเทพ',
      postalCode: '10110',
    },
    items: [
      {
        productId: 3,
        sku: 'COUGH-60',
        name: 'ยาแก้ไอสูตรไม่มีน้ำตาล',
        imageUrl: 'https://placehold.co/400x400/8b5cf6/white?text=Cough+Syrup',
        price: 55,
        quantity: 1,
        subtotal: 55,
      },
    ],
    subtotal: 55,
    shippingFee: 0,
    discountAmount: 0,
    totalAmount: 55,
    status: 'shipped',
    paymentMethod: 'promptpay',
    paymentStatus: 'paid',
    trackingNo: 'KEX1234567890',
    shippedAt: '2025-03-11T09:00:00Z',
    createdAt: '2025-03-10T14:20:00Z',
    updatedAt: '2025-03-11T09:00:00Z',
  },
  {
    id: 3,
    orderNo: 'RE250301012',
    lineUserId: 'U1234567890abcdef',
    customerName: 'นายสมชาย ใจดี',
    customerPhone: '081-234-5678',
    customerEmail: 'somchai@example.com',
    shippingAddress: {
      name: 'นายสมชาย ใจดี',
      phone: '081-234-5678',
      address: '123/45 ถ.สุขุมวิท ซ.15',
      district: 'คลองเตย',
      province: 'กรุงเทพ',
      postalCode: '10110',
    },
    items: [
      {
        productId: 7,
        sku: 'VITD-60',
        name: 'วิตามิน D3 1000 IU',
        imageUrl: 'https://placehold.co/400x400/6366f1/white?text=Vitamin+D',
        price: 299,
        quantity: 1,
        subtotal: 299,
      },
    ],
    subtotal: 299,
    shippingFee: 0,
    discountAmount: 0,
    totalAmount: 299,
    status: 'delivered',
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    deliveredAt: '2025-03-03T16:00:00Z',
    createdAt: '2025-03-01T11:00:00Z',
    updatedAt: '2025-03-03T16:00:00Z',
  },
];